# Start with a base image containing Java runtime
FROM openjdk:13-jdk-alpine
WORKDIR /app
COPY ./ /app/
RUN gradle clean build -x test --no-daemon --console plain

FROM openjdk:13-jdk-alpine

# Add Maintainer Info
LABEL maintainer="ucbabu@gmail.com"

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8080 available to the world outside this container
EXPOSE 8080

WORKDIR /app
COPY --from=build /app/build/libs/skaf-gra-springboot-app-*.jar /app/app.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app/app.jar"]
